export const infs: any [] = [
    
  {name:"Author",para:"Certainly listening no behaviour existence assurance situation",imagess:"../.../../../../../assets/images/img-2/image-33.png",calenderimg:"../../../../assets/images/img-2/calendar_month_20dp_FILL0_wght400_GRAD0_opsz20.svg",dates:"jul/15/2018",commentimg:"../../../../assets/images/img-2/forum_20dp_FILL0_wght400_GRAD0_opsz20.svg",commentnum:"01",eyeimg:"../../../../assets/images/img-2/visibility_20dp_FILL0_wght400_GRAD0_opsz20.svg",eyenum:"301"},
  {name:"Author",para:"Certainly listening no behaviour existence assurance situation",imagess:"../../../../assets/images/img-2/img-32.png",calenderimg:"../../../../assets/images/img-2/calendar_month_20dp_FILL0_wght400_GRAD0_opsz20.svg",dates:"jul/15/2018",commentimg:"../../../../assets/images/img-2/forum_20dp_FILL0_wght400_GRAD0_opsz20.svg",commentnum:"01",eyeimg:"../../../../assets/images/img-2/visibility_20dp_FILL0_wght400_GRAD0_opsz20.svg",eyenum:"301"},
  {name:"Author",para:"Certainly listening no behaviour existence assurance situation",imagess:"../.../../../../../assets/images/img-2/img-34.png",calenderimg:"../../../../assets/images/img-2/calendar_month_20dp_FILL0_wght400_GRAD0_opsz20.svg",dates:"jul/15/2018",commentimg:"../../../../assets/images/img-2/forum_20dp_FILL0_wght400_GRAD0_opsz20.svg",commentnum:"01",eyeimg:"../../../../assets/images/img-2/visibility_20dp_FILL0_wght400_GRAD0_opsz20.svg",eyenum:"301"},
  {name:"Author",para:"Certainly listening no behaviour existence assurance situation",imagess:"../.../../../../../assets/images/img-2/img-55.png",calenderimg:"../../../../assets/images/img-2/calendar_month_20dp_FILL0_wght400_GRAD0_opsz20.svg",dates:"jul/15/2018",commentimg:"../../../../assets/images/img-2/forum_20dp_FILL0_wght400_GRAD0_opsz20.svg",commentnum:"01",eyeimg:"../../../../assets/images/img-2/visibility_20dp_FILL0_wght400_GRAD0_opsz20.svg",eyenum:"301"},
  {name:"Author",para:"Certainly listening no behaviour existence assurance situation",imagess:"../.../../../../../assets/images/img-2/img-77.png",calenderimg:"../../../../assets/images/img-2/calendar_month_20dp_FILL0_wght400_GRAD0_opsz20.svg",dates:"jul/15/2018",commentimg:"../../../../assets/images/img-2/forum_20dp_FILL0_wght400_GRAD0_opsz20.svg",commentnum:"01",eyeimg:"../../../../assets/images/img-2/visibility_20dp_FILL0_wght400_GRAD0_opsz20.svg",eyenum:"301"},
  {name:"Author",para:"Certainly listening no behaviour existence assurance situation",imagess:"../.../../../../../assets/images/img-2/img-55.png",calenderimg:"../../../../assets/images/img-2/calendar_month_20dp_FILL0_wght400_GRAD0_opsz20.svg",dates:"jul/15/2018",commentimg:"../../../../assets/images/img-2/forum_20dp_FILL0_wght400_GRAD0_opsz20.svg",commentnum:"01",eyeimg:"../../../../assets/images/img-2/visibility_20dp_FILL0_wght400_GRAD0_opsz20.svg",eyenum:"301"},
  {name:"Author",para:"Certainly listening no behaviour existence assurance situation",imagess:"../.../../../../../assets/images/img-2/img-77.png",calenderimg:"../../../../assets/images/img-2/calendar_month_20dp_FILL0_wght400_GRAD0_opsz20.svg",dates:"jul/15/2018",commentimg:"../../../../assets/images/img-2/forum_20dp_FILL0_wght400_GRAD0_opsz20.svg",commentnum:"01",eyeimg:"../../../../assets/images/img-2/visibility_20dp_FILL0_wght400_GRAD0_opsz20.svg",eyenum:"301"}
  
  ]